{"id": "da05ece1-62e1-4ae2-9102-f25a34ebf090", "family": "shaft", "subtype": "simple_shaft_bored_chamfer", "file_name": "shaft_20_100_10.SLDPRT", "template": "docs/templates/shaft_simple_bored_template.SLDPRT", "units": "mm", "prompt": "Create a simple shaft (cylindrical) with outer diameter 20 mm, length 100 mm, a through axial bore of diameter 10 mm, and a 45° chamfer of 1 mm on the end edges (both ends) as in the template.", "template_inputs": {"SHAFT_OD": 20.0, "SHAFT_L": 100.0, "BORE_D": 10.0, "CHAMFER_L": 1.0, "CHAMFER_ANG": 45.0}, "notes": ["From screenshots: Sketch1 shows Ø20.00 mm for the outer cylinder; Boss-Extrude1 depth is 100.00 mm.", "Sketch2/Cut-Extrude1 shows Ø10.00 mm and the cut is Through All (axial bore).", "Chamfer1: Distance=1 mm, Angle=45°; select the circular edge on each end face so the chamfer applies to both ends."]}
